version: "3.8"

services:
  news-db-init:
    container_name: news-db-init
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - msanet
    environment:
      JAVA_OPTS: "-Xss256k"
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/news_db
  postgres:
    container_name: postgres
    image: "bitnami/postgresql"
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - msanet
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "news_db"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d news_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
networks:
  msanet:
    driver: bridge
