version: "3.8"

services:
  otus-service-db-init:
    container_name: otus-service-db-init
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    networks:
      - msanet
    environment:
      JAVA_OPTS: "-Xss256k"
      DATASOURCE_URL: jdbc:postgresql://db/mydb
      DATASOURCE_USERNAME: myuser
      DATASOURCE_PASSWORD: mypass
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - msanet
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
networks:
  msanet:
    driver: bridge
