version: "3.8"

services:
  otus-service-db-init:
    container_name: otus-service-db-init
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    networks:
      - msanet
    environment:
      JAVA_OPTS: "-Xss256k"
      DATASOURCE_URL: jdbc:postgresql://db/postgres
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: 123456
  db:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    networks:
      - msanet
    environment:
      POSTGRESQL_PASSWORD: 123456
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_DATABASE: postgres
networks:
  msanet:
    driver: bridge
