server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: otus-service-db-init
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  liquibase:
    change-log: db/db.changelog-master.yml
management:
  endpoint:
    health:
      probes.enabled: true
      livenessState.enabled: true
      readinessState.enabled: true
  endpoints:
    web:
      base-path: /
      path-mapping.health: health
